/* u52-mparam.h - GENERATED by bench/tune_u52; do not hand-edit
 * defaults. Thresholds in limbs of the smaller operand. */
#ifndef MUL_U52_T22_THRESHOLD
#define MUL_U52_T22_THRESHOLD 82
#endif
#ifndef MUL_U52_T33_THRESHOLD
#define MUL_U52_T33_THRESHOLD 618
#endif
#ifndef MUL_U52_T32_OK_THRESHOLD
#define MUL_U52_T32_OK_THRESHOLD 108
#endif
#ifndef MUL_U52_T42_OK_THRESHOLD
#define MUL_U52_T42_OK_THRESHOLD 132
#endif
