/* u52-mparam.h - GENERATED by bench/tune_u52; do not hand-edit
 * defaults. Thresholds in limbs of the smaller operand.
 * T22 updated from the tuned 82 per bench/fft16_vs_dispatch_sweep T22
 * scans (balanced 128-512 u64 limbs, solo-per-process, 2 runs): the
 * 90-100 plateau beats 82/84 by ~3.5% overall (96 nominally best in
 * both runs); 92 is a local pothole, the surface is non-convex (T22
 * also gates the canonneg folds). Re-run tune_u52 to revalidate. */
#ifndef MUL_U52_T22_THRESHOLD
#define MUL_U52_T22_THRESHOLD 96
#endif
#ifndef MUL_U52_T33_THRESHOLD
#define MUL_U52_T33_THRESHOLD 618
#endif
#ifndef MUL_U52_T32_OK_THRESHOLD
#define MUL_U52_T32_OK_THRESHOLD 108
#endif
#ifndef MUL_U52_T42_OK_THRESHOLD
#define MUL_U52_T42_OK_THRESHOLD 132
#endif
